<a href="https://colab.research.google.com/github/sangeeth938/ML-day1/blob/main/ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [2]:
import numpy as np
a=[1,2,3,4]
arr1=np.array(a)
b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print(type(a))
print(type(arr1))
print(type(b))
print(type(arr2))

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
import sys

s=range(1000)
print(s)

range(0, 1000)


In [5]:
print(random.s)
slice

NameError: ignored

In [11]:
print("size of each element in s:",sys.getsizeof(s))
print("complete size of s is", sys.getsizeof(s)*len(s))

size of each element in s: 8096
complete size of s is 8096000


In [12]:
import numpy as np
s=np.arange(1000)
print("size of s in bytes",  s.itemsize)
print("complete size of s is", s.itemsize*len(s))

size of s in bytes 8
complete size of s is 8000


In [19]:
#importing time module and trying to find the taken for an execution
import time
a=range(1000)
b=range(1000)
start=time.time()
ab=[(a*b) for a,b in zip(a,b)] #multiplication of items using list comprehend and zip is used for index multiplexing
end=time.time()
print("time taken for execution is",end-start)

time taken for execution is 0.0001761913299560547


In [18]:
#calculating execution time using numpy
import numpy as np
import time
arr1=np.arange(1000)
arr2=np.arange(1000)
start=time.time()
array_mul=arr1*arr2
end=time.time()
print("time taken for execution is",end-start)

time taken for execution is 7.891654968261719e-05


In [21]:
list1=[1,2,3,4]
arr=np.array(list1)
print(arr)

[1 2 3 4]


In [22]:
print(list1+1)

TypeError: ignored

In [23]:
print(arr+1)

[2 3 4 5]


In [24]:
print(arr)


[1 2 3 4]


In [25]:
print(arr-1)

[0 1 2 3]
