<a href="https://colab.research.google.com/github/sangeeth938/ML-day1/blob/main/ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np
a=[1,2,3,4]
arr1=np.array(a)
b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a))
print(type(arr1))
print(type(b))
print(type(arr2))

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import sys

s=range(1000)
print(s)

range(0, 1000)


In [ ]:
print(random.s)
slice

NameError: ignored

In [ ]:
print("size of each element in s:",sys.getsizeof(s))
print("complete size of s is", sys.getsizeof(s)*len(s))

size of each element in s: 8096
complete size of s is 8096000


In [ ]:
import numpy as np
s=np.arange(1000)
print("size of s in bytes",  s.itemsize)
print("complete size of s is", s.itemsize*len(s))

size of s in bytes 8
complete size of s is 8000


In [ ]:
#importing time module and trying to find the taken for an execution
import time
a=range(1000)
b=range(1000)
start=time.time()
ab=[(a*b) for a,b in zip(a,b)] #multiplication of items using list comprehend and zip is used for index multiplexing
end=time.time()
print("time taken for execution is",end-start)

time taken for execution is 0.0001761913299560547


In [ ]:
#calculating execution time using numpy
import numpy as np
import time
arr1=np.arange(1000)
arr2=np.arange(1000)
start=time.time()
array_mul=arr1*arr2
end=time.time()
print("time taken for execution is",end-start)

time taken for execution is 7.891654968261719e-05


In [ ]:
list1=[1,2,3,4]
arr=np.array(list1)
print(arr)

[1 2 3 4]


In [ ]:
print(list1+1)

TypeError: ignored

In [ ]:
print(arr+1)

[2 3 4 5]


In [ ]:
print(arr)


[1 2 3 4]


In [ ]:
print(arr-1)

[0 1 2 3]


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.zeros((2,2))
print(arr2)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
arr1= np.array([[1,2,3,4],[4,5,6,7]], ndmin=2)
print(arr1)  

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
a=[[1,2,3,4],[2,3,4,5]]
print(a)

[[1, 2, 3, 4], [2, 3, 4, 5]]


In [ ]:
import numpy as np
arr1= np.array(a,ndmin=2)
print(arr1)

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
print(a)


[[1, 2, 3, 4], [2, 3, 4, 5]]


In [ ]:
import numpy as  np
arr2= np.array(a,ndmin=10)
print(arr2)

[[[[[[[[[[1 2 3 4]
         [2 3 4 5]]]]]]]]]]


In [ ]:
import numpy as np
np.random.rand(3,3)

array([[0.81482489, 0.19373149, 0.30374561],
       [0.3790363 , 0.98737955, 0.13043909],
       [0.14920783, 0.25596438, 0.72223503]])

In [ ]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
sum=np.add(arr1,arr2)
print(arr1)
print(arr2)
print(sum)

[[0.31612059 0.6506383  0.77533801]
 [0.6062376  0.05363913 0.14786135]
 [0.68133347 0.09418332 0.45382418]]
[[0.84049238 0.91362813 0.18885022]
 [0.06079375 0.18508517 0.71082795]
 [0.43918339 0.91933836 0.88892438]]
[[1.15661298 1.56426643 0.96418822]
 [0.66703135 0.2387243  0.8586893 ]
 [1.12051687 1.01352168 1.34274856]]


In [ ]:
sub=np.subtract(arr1,arr2)
print(sub)

[[-0.52437179 -0.26298983  0.58648779]
 [ 0.54544386 -0.13144604 -0.5629666 ]
 [ 0.24215008 -0.82515504 -0.4351002 ]]


In [ ]:
print(arr1)

[[0.31612059 0.6506383  0.77533801]
 [0.6062376  0.05363913 0.14786135]
 [0.68133347 0.09418332 0.45382418]]


In [ ]:
arr1[1,1]

0.05363912868878162

In [ ]:
arr1[3,0]

IndexError: ignored

In [ ]:
np.arange(2,2)

array([], dtype=int64)

In [ ]:
#indexing and slicing

a=[1,2,3.4,"sangeeth",True,False,2+3j,0]
print(type(a))

<class 'list'>


In [ ]:
a[0]

1

In [ ]:
a[8]


IndexError: ignored

In [ ]:
a[:]

[1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0]

In [ ]:
a[0:8]

[1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0]

In [ ]:
a[2:6]

[3.4, 'sangeeth', True, False]

In [ ]:
a[:-1]

[1, 2, 3.4, 'sangeeth', True, False, (2+3j)]

In [ ]:
a[-1:-5]

[]

In [ ]:
a[-5:-1]

['sangeeth', True, False, (2+3j)]

In [ ]:
b= [1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0,1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0,1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0]
b[0:15:2]

[1, 3.4, True, (2+3j), 1, 3.4, True, (2+3j)]

In [ ]:
b[1:15:3]

[2, True, 0, 3.4, False]

In [ ]:
b.reverse()

In [ ]:
b

[0,
 (2+3j),
 False,
 True,
 'sangeeth',
 3.4,
 2,
 1,
 0,
 (2+3j),
 False,
 True,
 'sangeeth',
 3.4,
 2,
 1,
 0,
 (2+3j),
 False,
 True,
 'sangeeth',
 3.4,
 2,
 1]

In [ ]:
#Reshape an array

arr1= np.array([[1,2,3,4],[2,3,4,5]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
arr1.shape

(2, 4)

In [ ]:
arr1.reshape(1,8)

array([[1, 2, 3, 4, 2, 3, 4, 5]])

In [ ]:
arr1.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr1.reshape(2,6)

ValueError: ignored

#PANDAS- A Data handling mechanism. need to upload data and get the link to read the data