<a href="https://colab.research.google.com/github/sangeeth938/ML-day1/blob/main/ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np
a=[1,2,3,4]
arr1=np.array(a)
b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a))
print(type(arr1))
print(type(b))
print(type(arr2))

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import sys

s=range(1000)
print(s)

range(0, 1000)


In [ ]:
print(random.s)
slice

NameError: ignored

In [ ]:
print("size of each element in s:",sys.getsizeof(s))
print("complete size of s is", sys.getsizeof(s)*len(s))

size of each element in s: 8096
complete size of s is 8096000


In [ ]:
import numpy as np
s=np.arange(1000)
print("size of s in bytes",  s.itemsize)
print("complete size of s is", s.itemsize*len(s))

size of s in bytes 8
complete size of s is 8000


In [ ]:
#importing time module and trying to find the taken for an execution
import time
a=range(1000)
b=range(1000)
start=time.time()
ab=[(a*b) for a,b in zip(a,b)] #multiplication of items using list comprehend and zip is used for index multiplexing
end=time.time()
print("time taken for execution is",end-start)

time taken for execution is 0.0001761913299560547


In [ ]:
#calculating execution time using numpy
import numpy as np
import time
arr1=np.arange(1000)
arr2=np.arange(1000)
start=time.time()
array_mul=arr1*arr2
end=time.time()
print("time taken for execution is",end-start)

time taken for execution is 7.891654968261719e-05


In [ ]:
list1=[1,2,3,4]
arr=np.array(list1)
print(arr)

[1 2 3 4]


In [ ]:
print(list1+1)

TypeError: ignored

In [ ]:
print(arr+1)

[2 3 4 5]


In [ ]:
print(arr)


[1 2 3 4]


In [ ]:
print(arr-1)

[0 1 2 3]


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.zeros((2,2))
print(arr2)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
arr1= np.array([[1,2,3,4],[4,5,6,7]], ndmin=2)
print(arr1)  

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
a=[[1,2,3,4],[2,3,4,5]]
print(a)

[[1, 2, 3, 4], [2, 3, 4, 5]]


In [ ]:
import numpy as np
arr1= np.array(a,ndmin=2)
print(arr1)

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
print(a)


[[1, 2, 3, 4], [2, 3, 4, 5]]


In [ ]:
import numpy as  np
arr2= np.array(a,ndmin=10)
print(arr2)

[[[[[[[[[[1 2 3 4]
         [2 3 4 5]]]]]]]]]]


In [ ]:
import numpy as np
np.random.rand(3,3)

array([[0.81482489, 0.19373149, 0.30374561],
       [0.3790363 , 0.98737955, 0.13043909],
       [0.14920783, 0.25596438, 0.72223503]])

In [ ]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
sum=np.add(arr1,arr2)
print(arr1)
print(arr2)
print(sum)

[[0.31612059 0.6506383  0.77533801]
 [0.6062376  0.05363913 0.14786135]
 [0.68133347 0.09418332 0.45382418]]
[[0.84049238 0.91362813 0.18885022]
 [0.06079375 0.18508517 0.71082795]
 [0.43918339 0.91933836 0.88892438]]
[[1.15661298 1.56426643 0.96418822]
 [0.66703135 0.2387243  0.8586893 ]
 [1.12051687 1.01352168 1.34274856]]


In [ ]:
sub=np.subtract(arr1,arr2)
print(sub)

[[-0.52437179 -0.26298983  0.58648779]
 [ 0.54544386 -0.13144604 -0.5629666 ]
 [ 0.24215008 -0.82515504 -0.4351002 ]]


In [ ]:
print(arr1)

[[0.31612059 0.6506383  0.77533801]
 [0.6062376  0.05363913 0.14786135]
 [0.68133347 0.09418332 0.45382418]]


In [ ]:
arr1[1,1]

0.05363912868878162

In [ ]:
arr1[3,0]

IndexError: ignored

In [ ]:
np.arange(2,2)

array([], dtype=int64)

In [ ]:
#indexing and slicing

a=[1,2,3.4,"sangeeth",True,False,2+3j,0]
print(type(a))

<class 'list'>


In [ ]:
a[0]

1

In [ ]:
a[8]


IndexError: ignored

In [ ]:
a[:]

[1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0]

In [ ]:
a[0:8]

[1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0]

In [ ]:
a[2:6]

[3.4, 'sangeeth', True, False]

In [ ]:
a[:-1]

[1, 2, 3.4, 'sangeeth', True, False, (2+3j)]

In [ ]:
a[-1:-5]

[]

In [ ]:
a[-5:-1]

['sangeeth', True, False, (2+3j)]

In [ ]:
b= [1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0,1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0,1, 2, 3.4, 'sangeeth', True, False, (2+3j), 0]
b[0:15:2]

[1, 3.4, True, (2+3j), 1, 3.4, True, (2+3j)]

In [ ]:
b[1:15:3]

[2, True, 0, 3.4, False]

In [ ]:
b.reverse()

In [ ]:
b

[0,
 (2+3j),
 False,
 True,
 'sangeeth',
 3.4,
 2,
 1,
 0,
 (2+3j),
 False,
 True,
 'sangeeth',
 3.4,
 2,
 1,
 0,
 (2+3j),
 False,
 True,
 'sangeeth',
 3.4,
 2,
 1]

In [ ]:
#Reshape an array

arr1= np.array([[1,2,3,4],[2,3,4,5]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
arr1.shape

(2, 4)

In [ ]:
arr1.reshape(1,8)

array([[1, 2, 3, 4, 2, 3, 4, 5]])

In [ ]:
arr1.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr1.reshape(2,6)

ValueError: ignored

#PANDAS- A Data handling mechanism. need to upload data and get the link to read the data

In [3]:
import pandas as pd

In [4]:
data= pd.read_csv("/content/ipl_matches.csv")

In [5]:
data.head(10)

id  season       city  ...         umpire1        umpire2 umpire3
0   1    2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2    2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3    2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5    2017  Bangalore  ...             NaN            NaN     NaN
5   6    2017  Hyderabad  ...      A Deshmukh       NJ Llong     NaN
6   7    2017     Mumbai  ...     Nitin Menon      CK Nandan     NaN
7   8    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
8   9    2017       Pune  ...     AY Dandekar         S Ravi     NaN
9  10    2017     Mumbai  ...     Nitin Menon      CK Nandan     NaN

[10 rows x 18 columns]

In [6]:
data.head()

id  season       city  ...         umpire1        umpire2 umpire3
0   1    2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2    2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3    2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5    2017  Bangalore  ...             NaN            NaN     NaN

[5 rows x 18 columns]

In [7]:
data.tail()

id  season       city  ...          umpire1          umpire2 umpire3
631  632    2016     Raipur  ...   A Nand Kishore     BNJ Oxenford     NaN
632  633    2016  Bangalore  ...     AK Chaudhary  HDPK Dharmasena     NaN
633  634    2016      Delhi  ...        M Erasmus    C Shamshuddin     NaN
634  635    2016      Delhi  ...        M Erasmus        CK Nandan     NaN
635  636    2016  Bangalore  ...  HDPK Dharmasena     BNJ Oxenford     NaN

[5 rows x 18 columns]

In [8]:
data.tail(10)

id  season  ...          umpire2 umpire3
626  627    2016  ...        CK Nandan     NaN
627  628    2016  ...     BNJ Oxenford     NaN
628  629    2016  ...      Nitin Menon     NaN
629  630    2016  ...        CK Nandan     NaN
630  631    2016  ...        M Erasmus     NaN
631  632    2016  ...     BNJ Oxenford     NaN
632  633    2016  ...  HDPK Dharmasena     NaN
633  634    2016  ...    C Shamshuddin     NaN
634  635    2016  ...        CK Nandan     NaN
635  636    2016  ...     BNJ Oxenford     NaN

[10 rows x 18 columns]

In [11]:
data.shape

(636, 18)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               636 non-null    int64  
 1   season           636 non-null    int64  
 2   city             629 non-null    object 
 3   date             636 non-null    object 
 4   team1            636 non-null    object 
 5   team2            636 non-null    object 
 6   toss_winner      636 non-null    object 
 7   toss_decision    636 non-null    object 
 8   result           636 non-null    object 
 9   dl_applied       636 non-null    int64  
 10  winner           633 non-null    object 
 11  win_by_runs      636 non-null    int64  
 12  win_by_wickets   636 non-null    int64  
 13  player_of_match  633 non-null    object 
 14  venue            636 non-null    object 
 15  umpire1          635 non-null    object 
 16  umpire2          635 non-null    object 
 17  umpire3         

In [14]:
#description of the data

data.describe()

id       season  ...  win_by_wickets  umpire3
count  636.000000   636.000000  ...      636.000000      0.0
mean   318.500000  2012.490566  ...        3.372642      NaN
std    183.741666     2.773026  ...        3.420338      NaN
min      1.000000  2008.000000  ...        0.000000      NaN
25%    159.750000  2010.000000  ...        0.000000      NaN
50%    318.500000  2012.000000  ...        4.000000      NaN
75%    477.250000  2015.000000  ...        7.000000      NaN
max    636.000000  2017.000000  ...       10.000000      NaN

[8 rows x 6 columns]

In [20]:
#reading a html parser from the webpage and accesing content from it

web= pd.read_html("https://en.wikipedia.org/wiki/Machine_learning")[7]

In [21]:
web.head()

Authority control                  Authority control.1
0             General  Integrated Authority File (Germany)
1  National libraries                  United States Japan
2               Other                   Microsoft Academic

In [29]:
web = pd.read_html("https://en.wikipedia.org/wiki/States_and_union_territories_of_India")[3]

In [30]:
web.head()

State  ... Additional officiallanguages[39]
0     Andhra Pradesh  ...                                —
1  Arunachal Pradesh  ...                                —
2              Assam  ...                    Bengali, Bodo
3              Bihar  ...                             Urdu
4       Chhattisgarh  ...                    Chhattisgarhi

[5 rows x 11 columns]

In [31]:
web.shape

(28, 11)

In [32]:
web

State  ...                   Additional officiallanguages[39]
0      Andhra Pradesh  ...                                                  —
1   Arunachal Pradesh  ...                                                  —
2               Assam  ...                                      Bengali, Bodo
3               Bihar  ...                                               Urdu
4        Chhattisgarh  ...                                      Chhattisgarhi
5                 Goa  ...                                            Marathi
6             Gujarat  ...                                                  —
7             Haryana  ...                                    Punjabi[41][42]
8    Himachal Pradesh  ...                                       Sanskrit[44]
9           Jharkhand  ...  Angika, Bengali, Bhojpuri, Ho, Kharia, Khortha...
10          Karnataka  ...                                                  —
11             Kerala  ...                                        English[46]
12     Madhya Pradesh  ...                                                  —
13        Maharashtra  ...                                                  —
14            Manipur  ...                                            English
15          Meghalaya  ...                                           Khasi[a]
16            Mizoram  ...                                                  —
17           Nagaland  ...                                                  —
18             Odisha  ...                                                  —
19             Punjab  ...                                                  —
20          Rajasthan  ...                                            English
21             Sikkim  ...  Bhutia, Gurung, Lepcha, Limbu, Manggar, Mukhia...
22         Tamil Nadu  ...                                            English
23          Telangana  ...                                           Urdu[49]
24            Tripura  ...                                                  —
25      Uttar Pradesh  ...                                               Urdu
26        Uttarakhand  ...                                       Sanskrit[51]
27        West Bengal  ...        Hindi, Odia, Telugu, Punjabi, Santali, Urdu

[28 rows x 11 columns]

In [33]:
excel= pd.read_excel("/content/ex1.xlsx")

In [34]:
excel

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [35]:
excel.head()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [36]:
excel.shape

(3, 6)

In [37]:
excel.tail()


Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo