<a href="https://colab.research.google.com/github/sangeeth938/ML-day1/blob/main/ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [2]:
import numpy as np
a=[1,2,3,4]
arr1=np.array(a)
b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print(type(a))
print(type(arr1))
print(type(b))
print(type(arr2))

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>
